sudo: required
dist: trusty
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=pylint
install:
  - pip install tox
script: tox
notifications:
  slack:
    - onaio:snkNXgprD498qQv4DgRREKJF
